### ISSUE TITLE
skipmap: LoadOrStore is racy

### ISSUE THREAD

**Issue by lithdew** [zhangyunhao116/skipmap#1]
```go
func (s *Map) LoadOrStore(key T, value interface{}) (actual interface{}, loaded bool) {
	loadedval, ok := s.Load(key)
	if !ok {
		s.Store(key, value)
		return value, false
	}
	return loadedval, true
}
```

With the current implementation for `LoadOrStore`, any racing `Load*`'s under the same key may erroneously return different values as every racing caller to `Store` under the implementation of `LoadOrStore` may override the value stored under the provided key.

I'd like to discuss this, though I believe a way to remediate this behavior is to modify `(*Map).Store(key, value)` to accept a boolean `update`. If `update` is true, and a value is found under the given key, the value is overridden and returned directly. If `update` is false, and a value is found under the given key, the existing value under the key is returned directly.

All of this logic under the `update` boolean needs to be atomic as well which I am not 100% sure is possible with the current `Store` implementation. So if this change is to be made, there may be a need to have the following lines which can be found in the `Store` implementation below be modified to be an atomic compare-and-swap operation instead:

```go
nodeFound := s.findNode(key, &preds, &succs)
if nodeFound != nil { // indicating the key is already in the skip-list
	if !nodeFound.flags.Get(marked) {
		// We don't need to care about whether or not the node is fully linked,
		// just replace the value.
		nodeFound.storeVal(value)
		return
	}
	// If the node is marked, represents some other goroutines is in the process of deleting this node,
	// we need to add this node in next loop.
	continue
}
```

With the `update` boolean logic proposed above, `LoadOrStore` may simply just be a direct call to `(*Map).Store(key, value, update)` then with `update` set to false.

Another improvement I'd like to suggest is, instead of following the same API as sync.Map for `LoadOrStore` where a value is directly provided, have the value parameter be a `func() interface{}` such that the signature of `LoadOrStore` is:

```go
func (m *Map) LoadOrStore(key T, value func() interface{}) (interface{}, bool)
```

The reason for this is that the value that is intended to be stored under a provided key might be something that is expensive to compute. Suppose you have multiple goroutines racing on `LoadOrStore`; each goroutine would unnecessarily need to instantiate the expensive-to-compute value when really only the one goroutine that wins the race to store some value under the provided key needs to instantiate the expensive-to-compute value.

By changing the function signature to accept a value as a `func() interface{}` instead, only the one goroutine out of many possibly-racing goroutines that wins the race to store a given value under the key will perform the expensive computation.

**Comment by zhangyunhao116** [comment]
Thank you for reporting this issue!

It is certainly a problem, occurs when two goroutines access the same key at the same time. Because they can't find this key in the `skipmap`, so they will `Store` different values which can cause the race problem.

A practical solution is to change `LoadOrStore` to a modified `Store`. In the new version, the only change is that when it finds the key, it will return its value instead of changing the value (https://github.com/zhangyunhao116/skipmap/blob/master/skipmap.go#L136). When multiple goroutines access the same key at the same time, only one goroutine successfully inserted its value, other goroutines would be failed and then return the existing value.

1) About changing the `Store` implementation.  Great idea, but for now I am preferred keeping the implementation because when some repos want to replace `skipmap` with `sync.Map`, the same API can save lots of time.  It is more like a historical issue.

2) About changing the `LoadOrStore` signature. Because the input value is `interface{}`, maybe wrap the value by getter and setter is a better idea, the real data is just a field of the struct, we can use a Mutex to solve the data race(lazy generator). Same as above, keep the signature just to preserve compatibility with the existing `sync.Map`, there are so many repos are built on top of these APIs.

Let me know if I can be of any help :)

**Comment by zhangyunhao116** [comment]
updated: present a new API for this situation https://github.com/zhangyunhao116/skipmap/blob/master/skipmap.go#L355
